start of properties grammar and example check
rnveach/checkstyle-extras pull request #6
Opened 2022-06-12 02:21 UTC by rnveach

2022-06-12 02:21 UTC, rnveach commented
@nick-mancuso ping

2022-06-13 13:00 UTC, nick-mancuso requested changes
A few thoughts:

2022-06-13 13:00 UTC, nick-mancuso commented on src/test/resources/com/rnveach/tools/checkstyle/extras/printers/ExpectedProperty.txt
> +|       `--TEXT -> f). [4:93]
What do you think about extracting all text and concatenating it here so that we just have one TEXT node?

2022-06-13 13:00 UTC, nick-mancuso commented on src/main/java/com/rnveach/tools/checkstyle/extras/visitors/PropertyAstVisitor.java
> +    private void processChildrenAndCombineText(PropertyAstImpl parent,
Can't we just have a `combineText` method? Do we know based on parent node (calling visit method) that we just want to concatenate text and return one node only?

Such as method would have semantics to match, i.e. just create the first child then just concatenate all sibling text.

2022-06-13 13:00 UTC, nick-mancuso commented on src/test/resources/com/rnveach/tools/checkstyle/extras/printers/ExpectedProperty.txt
> +|       |--POUND -> # [24:0]
How about `COMMENT_DELIMITER -> #` and `COMMENT_DELIMITER -> !`? This would make things easier in checks.

2022-06-13 13:00 UTC, nick-mancuso commented on src/test/resources/com/rnveach/tools/checkstyle/extras/printers/ExpectedProperty.txt
> +|               |--TEXT ->  c [25:6]
Can't we just concatenate all text (siblings) here? Or is there some value to having a bunch of child nodes?

2022-06-14 00:19 UTC, rnveach commented on src/test/resources/com/rnveach/tools/checkstyle/extras/printers/ExpectedProperty.txt
> +|       |   `--TERMINATOR -> \n [49:8]
I agree. I do not see any extra value right now by having the text as children.

For the most part I plan to just be a bit over-expressive on the text and it's contents of the tree.It is a explicit text so it will always be `\\n` if they wish to know the text of the continuation.

2022-06-14 00:29 UTC, rnveach commented on src/test/resources/com/rnveach/tools/checkstyle/extras/printers/ExpectedProperty.txt
> +|               |--TEXT ->  c [25:6]
There is some reasoning but this is a gray area I am not fully sure of.

I kept escaped character split out so we know what is being escaped and user doesn't need to do their own counting to determine this. The grammar ensures escaped are counted and handled correctly, so maybe this is extra noise. I think they may be more pertinent to know when they are used in the key, but if we are forbidding any escapes, then we just need to search for `\`.

Assignments is not a true assignment at this point, so if I don't combine it with the others, I need to rename it so it isn't confused with the actual assignment. I was thinking since most times they aren't pure text, I would keep them out so they were clear. I was thinking somewhat along the lines that maybe there should be a check to look for "confusing" assignments as if someone ends a line and isn't careful, these non-assignments can become real assignments by accident.

2022-06-14 00:35 UTC, rnveach commented on src/test/resources/com/rnveach/tools/checkstyle/extras/printers/ExpectedProperty.txt
> +|       |--POUND -> # [24:0]
I am against giving them the exact same name. This makes it harder to differentiate the 2 starts of the comment, as they essentially become the same token through the name of the token. They are already identified as the same token by having `COMMENT` as a parent. The first child identifies the difference between the 2 if it is a pound or exclamation and can avoid examining the string for that determination by simple looking at the type.

I plan to add a check that all comments must avoid using `!` as it doesn't really look like a comment.

2022-06-14 00:43 UTC, rnveach commented on src/main/java/com/rnveach/tools/checkstyle/extras/visitors/PropertyAstVisitor.java
> +    private void processChildrenAndCombineText(PropertyAstImpl parent,
This doesn't create only 1 node. It looks for similar tokens next to each other. For example, there is some weird circumstances where we actually have 2 TEXTs next to each other and are not combined by default. This combines those 2 together while leaving the other tokens un-merged. The reasoning goes back to https://github.com/rnveach/checkstyle-extras/pull/6#discussion_r896273120 .

I think your understanding this and saying just to make this just do that work of combining nodes in the manner its doing now just after a normal call to `processChildren`. The simple reason it wasn't written like this is because I didn't want the tree to be already be added before re-arranging it. I would need to create `update` methods in the AST to move children and siblings around and re-assigning siblings and such. I was trying to keep to the methods we have in `DetailAST` but this may not be sensible.

I will re-look at it.

2022-06-14 00:46 UTC, rnveach commented on src/test/resources/com/rnveach/tools/checkstyle/extras/printers/ExpectedProperty.txt
> +|       `--TEXT -> f). [4:93]
https://github.com/rnveach/checkstyle-extras/pull/6#discussion_r896273120 was my original reasoning but this is a comment and not really used for anything. The only real difficulties is I wish to keep the `#` / `!` separate.

I think this makes sense to fix this.

2022-07-16 01:26 UTC, rnveach commented on src/test/resources/com/rnveach/tools/checkstyle/extras/printers/ExpectedProperty.txt
> +|       `--TEXT -> f). [4:93]
This was done. All comments are TEXT now.

2024-02-17 17:12 UTC, closed without merging